### PR TITLE
Upgrade to version 2.4.0

### PR DESCRIPTION
**Pull request by mlund**
Merge w. conda-forge

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mlund** [comment]
@conda-forge-admin, please rerender

**Comment by mlund** [comment]
I'm getting the build errors below for both linux and macos; it looks a c++/stl issue. I can normally compile on these platforms (TravisCI), albeit a C++17 compiler is required (Clang 9 is definitely enough as is gcc 8). Any ideas how to fix this for this new version of faunus? ping @conda-forge/core

**Comment by isuruf** [comment]
> it looks like a problem with c++/stl.

Are you sure? What's the error that you are getting?

**Comment by mlund** [comment]
## OSX build

I am not sure it is STL, but for the osx build, the [azure log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=167939&view=logs&j=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&t=63fa899e-c160-5185-75c4-c5fd30c90374&l=1038) points to the STL headers, or a mismatch between the compiler and Xcode:

~~~
In file included from /Users/runner/miniforge3/conda-bld/faunus_1590339407451/work/src/functionparser.cpp:1:
In file included from /Users/runner/miniforge3/conda-bld/faunus_1590339407451/work/src/functionparser.h:3:
In file included from /Users/runner/miniforge3/conda-bld/faunus_1590339407451/_build_env/bin/../include/c++/v1/string:504:
In file included from /Users/runner/miniforge3/conda-bld/faunus_1590339407451/_build_env/bin/../include/c++/v1/string_view:175:
In file included from /Users/runner/miniforge3/conda-bld/faunus_1590339407451/_build_env/bin/../include/c++/v1/__string:57:
In file included from /Users/runner/miniforge3/conda-bld/faunus_1590339407451/_build_env/bin/../include/c++/v1/algorithm:644:
/Users/runner/miniforge3/conda-bld/faunus_1590339407451/_build_env/bin/../include/c++/v1/functional:1416:29: error: 'operator delete' is unavailable: introduced in macOS 10.12
class _LIBCPP_EXCEPTION_ABI bad_function_call
                            ^
/Users/runner/miniforge3/conda-bld/faunus_1590339407451/_build_env/bin/../include/c++/v1/functional:1431:11: note: in implicit destructor for 'std::__1::bad_function_call' first required here
    throw bad_function_call();
          ^
~~~

Local development is usually done on osx or linux and I haven't seen this before.

## Linux build (fixed)

On the Azure linux build with gcc 7.5 the following error occurs on the `unittests` target. I cannot reproduce this error using gcc 7.5 on my locla ubuntu installation.

~~~
/home/conda/feedstock_root/build_artifacts/faunus_1590339403185/work/src/unittests.cpp:20:
/home/conda/feedstock_root/build_artifacts/faunus_1590339403185/work/_deps/nanobench-src/src/include/nanobench.h: In member function 'bool ankerl::nanobench::detail::LinuxPerformanceCounters::monitor(uint32_t, uint64_t, ankerl::nanobench::detail::LinuxPerformanceCounters::Target)':
/home/conda/feedstock_root/build_artifacts/faunus_1590339403185/work/_deps/nanobench-src/src/include/nanobench.h:1529:25: error: 'PERF_EVENT_IOC_ID' was not declared in this scope
     if (-1 == ioctl(fd, PERF_EVENT_IOC_ID, &id)) {
                         ^~~~~~~~~~~~~~~~~
~~~

**Comment by mlund** [comment]
Applying a pre-build patch, the linux build now passes. I still do not know how to fix the macOS build. ping @conda-forge-admin

**Comment by mlund** [comment]
I suspect that the macOS SDK would need to be elevated from 10.9 to 10.12 and the issue seems related to [this discussion](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/67).

**Comment by isuruf** [comment]
You need to rerender and add a run_constrained requirement as well. See https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

**Comment by mlund** [comment]
> > it looks like a problem with c++/stl.
> 
> Are you sure? What's the error that you are getting?

@isuruf Please see above. Can you think of a way to make the osx target work?

**Comment by isuruf** [comment]
Please remove the last commit and follow the instructions at https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

**Comment by mlund** [comment]
> Please remove the last commit and follow the instructions at https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

Thanks a lot, this took the build almost to the end, but I now got an [error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=170531&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445&l=1320) regarding macOS _10.14_ but still also _10.12_ for the `pyfaunus` target. I will try to increase the SDK to 10.14 and if it doesn't work disable the python target for the osx build.

**Comment by mlund** [comment]
@conda-forge-admin, please rerender

**Comment by mlund** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Looks like you never rerendered before. So those changes were not reflected correctly. Can you try removing 10.14 and rerendering again?

**Comment by mlund** [comment]
> Looks like you never rerendered before. So those changes were not reflected correctly. Can you try removing 10.14 and rerendering again?

@isuruf  You mean go back to 10.12 or 10.9? There was a re-rendering 13 days ago (see above).

**Comment by isuruf** [comment]
to 10.12

**Comment by mlund** [comment]
@conda-forge-admin, please rerender

**Comment by mlund** [comment]
@isuruf Great, it now works with 10.12! Thanks for your support.
